export const ACTIONS = {
    UPDATE_INCOMING_MESSAGES: 'UPDATE_INCOMING_MESSAGES',
    UPDATE_SELECTED_CHANNEL: 'UPDATE_SELECTED_CHANNEL',
    UPDATE_CHANNELS: 'UPDATE_CHANNELS',
    UPDATE_USERNAME: 'UPDATE_USERNAME',
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    UPDATE_USER_IN_CHANNEL: 'UPDATE_USER_IN_CHANNEL',
};