export const ACTIONS = {
    UPDATE_SELECTED_CHANNEL: 'UPDATE_SELECTED_CHANNEL',
    UPDATE_CHANNELS: 'UPDATE_CHANNELS',
    UPDATE_USERNAME: 'UPDATE_USERNAME',
    ADD_NEW_MESSAGE_TO_CHANNEL: 'ADD_NEW_MESSAGE_TO_CHANNEL',
    UPDATE_USERS: 'UPDATE_USERS',
    UPDATE_MESSAGES: 'UPDATE_MESSAGES',
    UPDATE_CHANNELS_DATA: 'UPDATE_CHANNELS_DATA',
    UPDATE_SELECTED_CHANNELS_DATA: 'UPDATE_SELECTED_CHANNELS_DATA'
};