export const ACTIONS = {
    UPDATE_SELECTED_CHANNEL: 'UPDATE_SELECTED_CHANNEL',
    UPDATE_CHANNELS: 'UPDATE_CHANNELS',
    UPDATE_USERNAME: 'UPDATE_USERNAME',
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    UPDATE_USERS: 'UPDATE_USERS',
    UPDATE_MESSAGES: 'UPDATE_MESSAGES'
};